### ISSUE TITLE
Sensu-server crash when upgrading to 0.17.0

### ISSUE THREAD

**Issue by Igorshp** [sensu/sensu#913]
Upgraded sensu server to 0.17.0 and saw the following crash happen:

```
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0/lib/sensu/server/process.rb:317:in `block in update_event_registry': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:458:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:458:in `dispatch_response'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:414:in `process_cmd'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:386:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0/lib/sensu/server/process.rb:23:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0/bin/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:23:in `load'
	from /opt/sensu/bin/sensu-server:23:in `<main>'
```

Stored_event contents:
```
{:output=>"Check CRITICAL: {\"message\":\"The service is down\"}\n", :status=>2, :issued=>1427484934, :handlers=>["default"], :flapping=>false, :occurrences=>298}
```

Check contents:
```
{:command=>"check-disco-service.rb -h 127.0.0.1 -p 3180", :subscribers=>["disco-service"], :handlers=>["default"], :interval=>30, :notification=>"disco-service is failing healthchecks", :name=>"disco-service_healthcheck", :issued=>1427796403, :executed=>1427796403, :output=>"Check CRITICAL: {\"message\":\"The service is down\"}\n", :status=>2, :duration=>0.632, :history=>["2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2"], :total_state_change=>0}
```

looks like the output format was changed somewhere between versions 0.12.6 and 0.17.0 making it non-backwards compatible.
This goes against semver versioning scheme.

Could someone with bit more knowledge about the situation comment on best way to fix this?

**Comment by nlopes** [comment]
Same here.

**Comment by Igorshp** [comment]
@nlopes you need to ensure that all clients are running same version.

**Comment by nlopes** [comment]
@Igorshp Already done that. Everything is on 0.17.1. I just tried a flushall in redis to see if it helps.

**Comment by Igorshp** [comment]
Ah yes. I had to flush redis as well.
Uchiwa was also broken, it coudnt display triggered events.

redis flush fixed it.

**Comment by nlopes** [comment]
@portertech I actually think there might be a regression here: https://github.com/sensu/sensu/blob/7c8ee11d7b9d0bd94848626818bb4809956e0b27/lib/sensu/server/process.rb#L314

Previously that check was:
https://github.com/sensu/sensu/compare/v0.12.0...master#diff-b1352d95ed2d2b3454a9cbf22e47a38aL442

Was that change from [:status] to [:check][:status] made on purpose, or was that unintended? I have a couple of checks (checks that worked in 0.12) that don't work anymore as they don't have a key [:check] in the json.

If this was intended, I would appreciate some help either figuring out if I should decommission these checks, or a way to replace them.

**Comment by nlopes** [comment]
This is the error I get with 0.17.1. If I manually patch process.rb to use [:status] everything works (afaik).

{"timestamp":"2015-04-08T20:43:23.216225+0000","level":"warn","message":"Added by nlopes for debugging purposes: {:output=>\"CheckMemory CRITICAL: Free Memory: 462.2 MB (5.76 %), Used Memory: 7555.23 MB (94.24 %)\\n\", :status=>2, :issued=>1428525743, :handlers=>[\"default\"], :flapping=>false, :occurrences=>1}","client":"<OBFUSCATED>"}

        /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.1/lib/sensu/server/process.rb:314:in block in update_event_registry': undefined method []' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:458:in call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:458:in dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:414:in process_cmd'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.6.0/lib/em-redis/redis_protocol.rb:386:in receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.1/lib/sensu/server/process.rb:23:in run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.1/bin/sensu-server:10:in <top (required)>'
        from /opt/sensu/bin/sensu-server:23:in load'
        from /opt/sensu/bin/sensu-server:23:in <main>'

**Comment by nlopes** [comment]
OK, tracked this down to a check I still had in one of the machines (config management wasn't tracking the deletion of that file). Ignore the issue above. I had to delete the check, restart the client, and then flushall in redis.

**Comment by portertech** [comment]
Ah! This is due to a change in the event data that is stored. We need to document the upgrade process, as the existing data structures are incomplete/incorrect. Will try to have these instructions up be EOD tomorrow :+1:

**Comment by rumstattd** [comment]
I'm hitting on this same issue after an upgrade of the sensu server.

Is there a document of the upgrade process?

**Comment by phumpal** [comment]
I ran into this issue upgrading from 0.13 to 0.20.  A `FLUSHALL` in Redis fixed it for me.

@rumstattd - a Google site search of sensuapp.org returns https://sensuapp.org/docs/0.16/upgrading

@portertech are the upgrade instructions only relevant for versions <= 0.16?

**Comment by calebhailey** [comment]
Closing due to inactivity (mostly on our part), and because this shouldn't be an issue unless users are upgrading from super old versions of Sensu. Please feel free to create a new issue if this matter is not resolved, in which case we'll revisit the upgrade documentation. #monitoringlove
