### ISSUE TITLE
0.26 sensu server start problem

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1437]
my cookbook first setups and starts the server and after that the client is configured and started. This was working fine in the past but 0.26 seems to need client attributes for the server:
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.1.0/lib/sensu/settings/loader.rb:177:in `load_client_overrides': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.1.0/lib/sensu/settings/loader.rb:186:in `load_overrides!'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.1.0/lib/sensu/settings.rb:30:in `load'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.1.0/lib/sensu/settings.rb:43:in `get'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/lib/sensu/daemon.rb:133:in `load_settings'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/lib/sensu/daemon.rb:53:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/lib/sensu/server/process.rb:42:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/lib/sensu/server/process.rb:30:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/lib/sensu/server/process.rb:30:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.0/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
```

**Comment by cwjohnston** [comment]
@runningman84 thanks for reporting this regression. I've opened sensu/sensu-settings#45 for a fix.

**Comment by cwjohnston** [comment]
Fix released in Sensu 0.26.1
